[project]
name = "azure-example-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Balázs", email = "nemeth.balazs.vince@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.3",
    "uvicorn>=0.42.0",
]

[build-system]
requires = ["uv_build>=0.10.7,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipykernel>=7.2.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.2",
]
